language: objective-c
osx_image: xcode10.2
install:
  - ./install_swiftlint.sh
script:
  - gem install travis
  - travis lint .travis.yml --no-interactive
  - swiftlint
  - xcodebuild clean build -project ipa-uploader.xcodeproj -scheme Debug -destination "platform=macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO